/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Class.Koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class MainMenu extends javax.swing.JFrame {
DefaultTableModel tb;
DefaultTableModel tb2;
DefaultTableModel tb3;
Koneksi conn= new Koneksi();
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        tabelmodel();
        tabelmodelnormalisasi();
        tabelmodelPERINGKAT();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new usu.widget.Panel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jspAlternatif = new javax.swing.JScrollPane();
        pnAlternatif = new usu.widget.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlternatif = new javax.swing.JTable();
        tfAlternatif = new javax.swing.JLabel();
        jspNormalisasi = new javax.swing.JScrollPane();
        panel3 = new usu.widget.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNormalisasi = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jspPerangkingan = new javax.swing.JScrollPane();
        panel4 = new usu.widget.Panel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPerangkingan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jspTambahData = new javax.swing.JScrollPane();
        pnTambahData = new usu.widget.Panel();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(46, 216, 113));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 79));

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistem Pendukung Keputusan");

        jLabel2.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MEtode SAW");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(1046, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        jButton1.setText("Tambah Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton4.setText("Tabel Alternatif");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jButton2.setText("Normalisasi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setText("Perangkingan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new java.awt.CardLayout());

        pnAlternatif.setPreferredSize(new java.awt.Dimension(1268, 751));

        tblAlternatif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Penghasilan", "Jaminan", "Status Usaha", "Kondisi Usaha", "Kepribadian", "Harta Milik", "Kemampuan", "Tanggungan", "Kepemilikan Rumah", "Penghasilan Tambahan"
            }
        ));
        tblAlternatif.setPreferredSize(new java.awt.Dimension(1268, 751));
        jScrollPane1.setViewportView(tblAlternatif);

        tfAlternatif.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfAlternatif.setText("Tabel Alternatif");

        javax.swing.GroupLayout pnAlternatifLayout = new javax.swing.GroupLayout(pnAlternatif);
        pnAlternatif.setLayout(pnAlternatifLayout);
        pnAlternatifLayout.setHorizontalGroup(
            pnAlternatifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAlternatifLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAlternatifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfAlternatif)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnAlternatifLayout.setVerticalGroup(
            pnAlternatifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAlternatifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfAlternatif)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        jspAlternatif.setViewportView(pnAlternatif);

        jPanel1.add(jspAlternatif, "card6");

        jspNormalisasi.setPreferredSize(new java.awt.Dimension(1270, 753));

        panel3.setPreferredSize(new java.awt.Dimension(1268, 751));

        tblNormalisasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNormalisasi.setPreferredSize(new java.awt.Dimension(1168, 751));
        tblNormalisasi.setRowSorter(null);
        jScrollPane2.setViewportView(tblNormalisasi);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tabel Normalisasi");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        jspNormalisasi.setViewportView(panel3);

        jPanel1.add(jspNormalisasi, "card7");

        jspPerangkingan.setPreferredSize(new java.awt.Dimension(1270, 753));

        panel4.setPreferredSize(new java.awt.Dimension(1270, 753));

        tblPerangkingan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPerangkingan.setPreferredSize(new java.awt.Dimension(1268, 751));
        jScrollPane3.setViewportView(tblPerangkingan);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tabel Perangkingan");

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        jspPerangkingan.setViewportView(panel4);

        jPanel1.add(jspPerangkingan, "card8");

        pnTambahData.setBackground(new java.awt.Color(255, 255, 204));

        jPanel5.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jTextField1.setText("Masukkan Nama");
        jPanel5.add(jTextField1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Penghasilan", "1-<3 Juta", "3-<5 juta", "5-<7 juta", ">9 Juta", " " }));
        jPanel5.add(jComboBox1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jaminan Kredit", "<10 Juta", ">10 Juta - 25 Juta", ">25 Juta - 35 Juta", ">35 Juta - 50 Juta", ">50 Juta" }));
        jPanel5.add(jComboBox2);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Status Usaha", "Milik Bersama", "Milik Keluarga", "Milik Pribadi" }));
        jPanel5.add(jComboBox3);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kondisi Usaha", "Usaha Macet", "Usaha Diragukan", "Usaha Mulai Berkembang", "Usaha Berkembang", "Usaha Berkembang Pesat" }));
        jPanel5.add(jComboBox4);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kepribadian Nasabah", "Sangat Kurang", "Kurang", "Cukup", "Baik", "Sangat Baik" }));
        jPanel5.add(jComboBox5);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Harta Milik", ">25 Juta", ">50 Juta", ">75 Juta", ">100 Juta", ">125 Juta" }));
        jPanel5.add(jComboBox6);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kemampuan Melunasi Hutang", "Sangat Kurang", "Kurang", "Cukup", "Baik", "Sangat Baik" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox7);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggungan Hidup", ">11 Orang", "9-11 Orang", "6-8 Orang", "3-5 Orang", "1-2 Orang" }));
        jPanel5.add(jComboBox8);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kepemilikan Rumah", "Kontrak", "Ikut Orang Tua", "Milik Pribadi" }));
        jPanel5.add(jComboBox9);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kepemilikan Rumah", ">1 Juta", ">2 Juta", ">3 Juta", ">4 Juta", ">5 Juta" }));
        jPanel5.add(jComboBox10);

        jButton5.setText("Simpan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 153));
        jPanel6.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel6.setText("Nama");
        jPanel6.add(jLabel6);

        jLabel7.setText("Penghasilan");
        jPanel6.add(jLabel7);

        jLabel8.setText("Jaminan Kredit");
        jPanel6.add(jLabel8);

        jLabel9.setText("Status Usaha");
        jPanel6.add(jLabel9);

        jLabel10.setText("Kondisi Usaha");
        jPanel6.add(jLabel10);

        jLabel11.setText("Kepribadian Nasabah");
        jPanel6.add(jLabel11);

        jLabel12.setText("Harta Milik");
        jPanel6.add(jLabel12);

        jLabel13.setText("Kemampuan Pelunasan");
        jPanel6.add(jLabel13);

        jLabel14.setText("Tanggungan Hidup");
        jPanel6.add(jLabel14);

        jLabel15.setText("Kepemilikan Rumah");
        jPanel6.add(jLabel15);

        jLabel16.setText("Penghasilan Tambahan");
        jPanel6.add(jLabel16);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Form Tambah Data ");

        javax.swing.GroupLayout pnTambahDataLayout = new javax.swing.GroupLayout(pnTambahData);
        pnTambahData.setLayout(pnTambahDataLayout);
        pnTambahDataLayout.setHorizontalGroup(
            pnTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTambahDataLayout.createSequentialGroup()
                .addGroup(pnTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTambahDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTambahDataLayout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)))
                    .addGroup(pnTambahDataLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton5)))
                .addContainerGap(2208, Short.MAX_VALUE))
        );
        pnTambahDataLayout.setVerticalGroup(
            pnTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTambahDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jButton5)
                .addContainerGap(392, Short.MAX_VALUE))
        );

        jspTambahData.setViewportView(pnTambahData);

        jPanel1.add(jspTambahData, "card2");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       jspTambahData.setVisible(true);
        jspAlternatif.setVisible(false);
        jspNormalisasi.setVisible(false);
        jspPerangkingan.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       jspAlternatif.setVisible(true);
        jspTambahData.setVisible(false);
        jspNormalisasi.setVisible(false);
        jspPerangkingan.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        normalisasi();
        jspNormalisasi.setVisible(true);
        jspAlternatif.setVisible(false);
        jspTambahData.setVisible(false);
        jspPerangkingan.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cariperingkat();
        jspAlternatif.setVisible(false);
        jspTambahData.setVisible(false);
        jspNormalisasi.setVisible(false);
        jspPerangkingan.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JScrollPane jspAlternatif;
    private javax.swing.JScrollPane jspNormalisasi;
    private javax.swing.JScrollPane jspPerangkingan;
    private javax.swing.JScrollPane jspTambahData;
    private usu.widget.Panel panel1;
    private usu.widget.Panel panel3;
    private usu.widget.Panel panel4;
    private usu.widget.Panel pnAlternatif;
    private usu.widget.Panel pnTambahData;
    private javax.swing.JTable tblAlternatif;
    private javax.swing.JTable tblNormalisasi;
    private javax.swing.JTable tblPerangkingan;
    private javax.swing.JLabel tfAlternatif;
    // End of variables declaration//GEN-END:variables
public void tabelmodel(){
       tb =new DefaultTableModel();
       tb.addColumn("Nama");
       tb.addColumn("Kreteria 1");
       tb.addColumn("Kreteria 2");
       tb.addColumn("Kreteria 3");
       tb.addColumn("Kreteria 4");
       tb.addColumn("Kreteria 5");
       tb.addColumn("Kreteria 6");
       tb.addColumn("Kreteria 7");
       tb.addColumn("Kreteria 8");
       tb.addColumn("Kreteria 9");
       tb.addColumn("Kreteria 10");
       tblAlternatif.setModel(tb);
        try {
           
   
         ResultSet res = conn.ambilData("select *from tbl_alternatif ");
        while (res.next()){
                    tb.addRow(
                            new Object[]{
                                res.getString(1),
                                res.getString(2),
                                res.getString(3),
                                res.getString(4),
                                res.getString(5),
                                res.getString(6),
                                res.getString(7),
                                res.getString(8),
                                res.getString(9),
                                res.getString(10),
                                res.getString(11)
                            });
                } 
      
        tblAlternatif.setModel(tb);
          } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, ex);
        }   
     }
public void tabelmodelnormalisasi(){
       tb2 =new DefaultTableModel();
       tb2.addColumn("No.");
       tb2.addColumn("Nama");
       tb2.addColumn("Kreteria 1");
       tb2.addColumn("Kreteria 2");
       tb2.addColumn("Kreteria 3");
       tb2.addColumn("Kreteria 4");
       tb2.addColumn("Kreteria 5");
       tb2.addColumn("Kreteria 6");
       tb2.addColumn("Kreteria 7");
       tb2.addColumn("Kreteria 8");
       tb2.addColumn("Kreteria 9");
       tb2.addColumn("Kreteria 10");
       tblNormalisasi.setModel(tb2);
       }
public  void normalisasi(){
       LinkedList max=new LinkedList();
       LinkedList mm=new LinkedList();
   try {
           
   
         ResultSet res = conn.ambilData("select 	max(C1),"+ 
                 "max(C2), "+
                 "max(C3), "+
                 "max(C4), "+
                 "max(C5), "+
                 "max(C6), "+
                 "max(C7), "+
                 "max(C8), "+
                 "max(C9), "+
                 "max(C10)"+
	"from "+
	"tbl_alternatif ");
        while (res.next()){
                    max.add(res.getString(1));
                    max.add(res.getString(2));
                    max.add(res.getString(3));
                    max.add(res.getString(4));
                    max.add(res.getString(5));
                    max.add(res.getString(6));
                    max.add(res.getString(7));
                    max.add(res.getString(8));
                    max.add(res.getString(9));
                    max.add(res.getString(10));
                } 
        ResultSet res2 = conn.ambilData("select *"+
	"from "+
	"tbl_alternatif ");
        tabelmodelnormalisasi();
        while (res2.next()){
            tb2.addRow(new Object[]{
                res2.getString(1),
                res2.getString(2),
                (res2.getFloat(3)/Float.valueOf(max.get(0).toString())),
                (res2.getFloat(4)/Float.valueOf(max.get(1).toString())),
                (res2.getFloat(5)/Float.valueOf(max.get(2).toString())),
                (res2.getFloat(6)/Float.valueOf(max.get(3).toString())),
                (res2.getFloat(7)/Float.valueOf(max.get(4).toString())),
                (res2.getFloat(8)/Float.valueOf(max.get(5).toString())),
                (res2.getFloat(9)/Float.valueOf(max.get(6).toString())),
                (res2.getFloat(10)/Float.valueOf(max.get(7).toString())),
                (res2.getFloat(11)/Float.valueOf(max.get(8).toString())),
                (res2.getFloat(12)/Float.valueOf(max.get(9).toString())),
                
            });
                          
        }  
      
           } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, ex);
        }   
   }
public void tabelmodelPERINGKAT(){
        try {
            tb3 =new DefaultTableModel();
            tb3.addColumn("NAMA");
            tb3.addColumn("NILAI ");
            tblPerangkingan.setModel(tb3);
               ResultSet res = conn.ambilData("select *from tbl_peringkat order by nilai desc");
             while (res.next()){
                         tb3.addRow(new Object[]{res.getString(1),res.getString(2)}); 
                     }
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
   public void cariperingkat(){
        try {
            
       LinkedList mm=new LinkedList();
            ResultSet res3 = conn.ambilData("select * from tbl_bobot");
               tabelmodelPERINGKAT();
               while (res3.next()){
                           mm.add(res3.getString(1));
                           mm.add(res3.getString(2));
                           mm.add(res3.getString(3));
                           mm.add(res3.getString(4));
                           mm.add(res3.getString(5));
                           mm.add(res3.getString(6));
                           mm.add(res3.getString(7));
                           mm.add(res3.getString(8));
                           mm.add(res3.getString(9));
                           mm.add(res3.getString(10));
               }
            for (int t = 0; t < tblNormalisasi.getRowCount(); t++) {
              
            String sql = "delete from tbl_peringkat WHERE Nama= Nama";
               conn.simpanData(sql);
            }
            for (int x = 0; x < tblNormalisasi.getRowCount(); x++) {
               double r1;
               double r2;
               double r3;
               double r4;
               double r5;
               double r6;
               double r7;
               double r8;
               double r9;
               double r10;
               double w;
                r1 = (Float.valueOf(tblNormalisasi.getValueAt(x, 2).toString())*Float.valueOf(mm.get(0).toString()));
                r2=(Float.valueOf(tblNormalisasi.getValueAt(x, 3).toString())*Float.valueOf(mm.get(1).toString()));
                r3=(Float.valueOf(tblNormalisasi.getValueAt(x, 4).toString())*Float.valueOf(mm.get(2).toString()));
                r4=(Float.valueOf(tblNormalisasi.getValueAt(x, 5).toString())*Float.valueOf(mm.get(3).toString()));
                r5=(Float.valueOf(tblNormalisasi.getValueAt(x, 6).toString())*Float.valueOf(mm.get(4).toString()));
                r6=(Float.valueOf(tblNormalisasi.getValueAt(x, 7).toString())*Float.valueOf(mm.get(5).toString()));
                r7=(Float.valueOf(tblNormalisasi.getValueAt(x, 8).toString())*Float.valueOf(mm.get(6).toString()));
                r8=(Float.valueOf(tblNormalisasi.getValueAt(x, 9).toString())*Float.valueOf(mm.get(7).toString()));
                r9=(Float.valueOf(tblNormalisasi.getValueAt(x, 10).toString())*Float.valueOf(mm.get(8).toString()));
                r10=(Float.valueOf(tblNormalisasi.getValueAt(x, 11).toString())*Float.valueOf(mm.get(9).toString()));
                
                w=r1+r2+r3+r4+r5+r6+r7+r8+r9+r10;
            String sql = "insert into tbl_peringkat  values"+
             "('"+tblNormalisasi.getValueAt(x, 0).toString()+"', "+
             "'"+w+"')";
               conn.simpanData(sql);
            }
            tabelmodelPERINGKAT();
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, ex);
        }
       }
//   public int simpan(){        
//        String sql="insert into tbl_kriteria "+
//	"values"+
//	"('"+jTextField1.getText()+"', "+
//	"'"+jTextField2.getText()+"', "+
//	"'"+jTextField3.getText()+"', "+
//	"'"+jTextField4.getText()+"', "+
//        "'"+jTextField5.getText()+"'"+
//	")";               
//        conn.simpanData(sql);
//       return 0;
//    }
}
