/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Class.Koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class MainMenu extends javax.swing.JFrame {
DefaultTableModel tb;
DefaultTableModel tb2;
DefaultTableModel tb3;
int bb1, bb2, bb3, bb4, bb5, bb6, bb7, bb8, bb9, bb10;
Koneksi conn= new Koneksi();
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        tabelmodel();
        tabelmodelnormalisasi();
        tabelmodelPERINGKAT();
        jspHome.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new usu.widget.Panel();
        panel6 = new usu.widget.Panel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jspHome = new javax.swing.JScrollPane();
        panel2 = new usu.widget.Panel();
        jspTambahData = new usu.widget.Panel();
        jPanel5 = new javax.swing.JPanel();
        tfNama = new javax.swing.JTextField();
        cbPenghasilan = new javax.swing.JComboBox<>();
        cbJaminan = new javax.swing.JComboBox<>();
        cbStatus = new javax.swing.JComboBox<>();
        cbKondisi = new javax.swing.JComboBox<>();
        cbKepribadian = new javax.swing.JComboBox<>();
        cbHarta = new javax.swing.JComboBox<>();
        cbKemampuan = new javax.swing.JComboBox<>();
        cbTanggungan = new javax.swing.JComboBox<>();
        cbKepemilikan = new javax.swing.JComboBox<>();
        cbPTambahan = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        button1 = new usu.widget.Button();
        jspPerangkingan = new usu.widget.Panel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPerangkingan = new javax.swing.JTable();
        jspAlternatif = new usu.widget.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlternatif = new javax.swing.JTable();
        jspNormalisasi = new usu.widget.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNormalisasi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(17, 88, 51));
        panel1.setPreferredSize(new java.awt.Dimension(1366, 760));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel6.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/image/Header.png"))); // NOI18N
        panel6.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_TILED);
        panel6.setPreferredSize(new java.awt.Dimension(1366, 149));

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );

        panel1.add(panel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        jPanel4.setAlignmentX(0.0F);
        jPanel4.setAlignmentY(0.0F);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        btnHome.setBackground(new java.awt.Color(204, 255, 102));
        btnHome.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnHome.setText("Beranda");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel3.add(btnHome);

        jButton1.setBackground(new java.awt.Color(204, 255, 102));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton1.setText("Tambah Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton4.setBackground(new java.awt.Color(204, 255, 102));
        jButton4.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton4.setText("Alternatif");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jButton2.setBackground(new java.awt.Color(204, 255, 102));
        jButton2.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton2.setText("Normalisasi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setBackground(new java.awt.Color(204, 255, 102));
        jButton3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton3.setText("Perangkingan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        panel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 140, 570));
        jPanel4.getAccessibleContext().setAccessibleName("");

        jPanel1.setLayout(new java.awt.CardLayout());

        jspHome.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panel2.setBackground(new java.awt.Color(153, 0, 204));
        panel2.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/image/bgHome1.png"))); // NOI18N
        panel2.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_TILED);
        panel2.setPreferredSize(new java.awt.Dimension(1268, 610));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jspHome.setViewportView(panel2);

        jPanel1.add(jspHome, "card6");

        jspTambahData.setBackground(new java.awt.Color(255, 255, 204));
        jspTambahData.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/image/frmTambahData2.png"))); // NOI18N
        jspTambahData.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        jspTambahData.setMaximumSize(new java.awt.Dimension(1268, 750));
        jspTambahData.setPreferredSize(new java.awt.Dimension(1268, 610));
        jspTambahData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(46, 204, 113));
        jPanel5.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        tfNama.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        tfNama.setText("Masukkan Nama");
        jPanel5.add(tfNama);

        cbPenghasilan.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        cbPenghasilan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Penghasilan", "1-<3 Juta", "3-<5 juta", "5-<7 juta", ">9 Juta", " " }));
        cbPenghasilan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPenghasilanItemStateChanged(evt);
            }
        });
        cbPenghasilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPenghasilanActionPerformed(evt);
            }
        });
        jPanel5.add(cbPenghasilan);

        cbJaminan.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        cbJaminan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jaminan Kredit", "<10 Juta", ">10 Juta - 25 Juta", ">25 Juta - 35 Juta", ">35 Juta - 50 Juta", ">50 Juta" }));
        jPanel5.add(cbJaminan);

        cbStatus.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Status Usaha", "Milik Bersama", "Milik Keluarga", "Milik Pribadi" }));
        jPanel5.add(cbStatus);

        cbKondisi.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        cbKondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kondisi Usaha", "Usaha Macet", "Usaha Diragukan", "Usaha Mulai Berkembang", "Usaha Berkembang", "Usaha Berkembang Pesat" }));
        jPanel5.add(cbKondisi);

        cbKepribadian.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        cbKepribadian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kepribadian Nasabah", "Sangat Kurang", "Kurang", "Cukup", "Baik", "Sangat Baik" }));
        jPanel5.add(cbKepribadian);

        cbHarta.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        cbHarta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Harta Milik", ">25 Juta", ">50 Juta", ">75 Juta", ">100 Juta", ">125 Juta" }));
        jPanel5.add(cbHarta);

        cbKemampuan.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        cbKemampuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kemampuan Melunasi Hutang", "Sangat Kurang", "Kurang", "Cukup", "Baik", "Sangat Baik" }));
        cbKemampuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKemampuanActionPerformed(evt);
            }
        });
        jPanel5.add(cbKemampuan);

        cbTanggungan.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        cbTanggungan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggungan Hidup", ">11 Orang", "9-11 Orang", "6-8 Orang", "3-5 Orang", "1-2 Orang" }));
        jPanel5.add(cbTanggungan);

        cbKepemilikan.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        cbKepemilikan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kepemilikan Rumah", "Kontrak", "Ikut Orang Tua", "Milik Pribadi" }));
        jPanel5.add(cbKepemilikan);

        cbPTambahan.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        cbPTambahan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kepemilikan Rumah", ">1 Juta", ">2 Juta", ">3 Juta", ">4 Juta", ">5 Juta" }));
        jPanel5.add(cbPTambahan);

        jspTambahData.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 248, 304));

        jPanel2.setBackground(new java.awt.Color(46, 204, 113));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        jButton5.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        jButton5.setText("Simpan");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        button1.setText("Batal");
        button1.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        jPanel2.add(button1);

        jspTambahData.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 270, 40));

        jPanel1.add(jspTambahData, "card7");

        jspPerangkingan.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/image/frmRangking.png"))); // NOI18N
        jspPerangkingan.setPreferredSize(new java.awt.Dimension(1268, 610));
        jspPerangkingan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPerangkingan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPerangkingan.setPreferredSize(new java.awt.Dimension(1268, 751));
        jScrollPane3.setViewportView(tblPerangkingan);

        jspPerangkingan.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 125, 1160, 330));

        jPanel1.add(jspPerangkingan, "card7");

        jspAlternatif.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/image/frmAlternatif.png"))); // NOI18N
        jspAlternatif.setPreferredSize(new java.awt.Dimension(1268, 610));
        jspAlternatif.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAlternatif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Penghasilan", "Jaminan", "Status Usaha", "Kondisi Usaha", "Kepribadian", "Harta Milik", "Kemampuan", "Tanggungan", "Kepemilikan Rumah", "Penghasilan Tambahan"
            }
        ));
        tblAlternatif.setPreferredSize(new java.awt.Dimension(1268, 751));
        jScrollPane1.setViewportView(tblAlternatif);

        jspAlternatif.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 125, 1252, 340));

        jPanel1.add(jspAlternatif, "card7");

        jspNormalisasi.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/image/frmNormalisasi.png"))); // NOI18N
        jspNormalisasi.setPreferredSize(new java.awt.Dimension(1268, 610));
        jspNormalisasi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNormalisasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNormalisasi.setPreferredSize(new java.awt.Dimension(1168, 751));
        jScrollPane2.setViewportView(tblNormalisasi);

        jspNormalisasi.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 125, 1180, 330));

        jPanel1.add(jspNormalisasi, "card7");

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 149, 1230, 570));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jspHome.setVisible(false);
       jspTambahData.setVisible(true);
        jspAlternatif.setVisible(false);
        jspNormalisasi.setVisible(false);
        jspPerangkingan.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        tabelmodel();
        jspHome.setVisible(false);
       jspAlternatif.setVisible(true);
        jspTambahData.setVisible(false);
        jspNormalisasi.setVisible(false);
        jspPerangkingan.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cbKemampuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKemampuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKemampuanActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        simpan();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        normalisasi();
        jspHome.setVisible(false);
        jspNormalisasi.setVisible(true);
        jspAlternatif.setVisible(false);
        jspTambahData.setVisible(false);
        jspPerangkingan.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cariperingkat();
        jspHome.setVisible(false);
        jspAlternatif.setVisible(false);
        jspTambahData.setVisible(false);
        jspNormalisasi.setVisible(false);
        jspPerangkingan.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbPenghasilanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPenghasilanItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbPenghasilanItemStateChanged

    private void cbPenghasilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPenghasilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPenghasilanActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        jspHome.setVisible(true);
        jspAlternatif.setVisible(false);
        jspTambahData.setVisible(false);
        jspNormalisasi.setVisible(false);
        jspPerangkingan.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private usu.widget.Button button1;
    private javax.swing.JComboBox<String> cbHarta;
    private javax.swing.JComboBox<String> cbJaminan;
    private javax.swing.JComboBox<String> cbKemampuan;
    private javax.swing.JComboBox<String> cbKepemilikan;
    private javax.swing.JComboBox<String> cbKepribadian;
    private javax.swing.JComboBox<String> cbKondisi;
    private javax.swing.JComboBox<String> cbPTambahan;
    private javax.swing.JComboBox<String> cbPenghasilan;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JComboBox<String> cbTanggungan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private usu.widget.Panel jspAlternatif;
    private javax.swing.JScrollPane jspHome;
    private usu.widget.Panel jspNormalisasi;
    private usu.widget.Panel jspPerangkingan;
    private usu.widget.Panel jspTambahData;
    private usu.widget.Panel panel1;
    private usu.widget.Panel panel2;
    private usu.widget.Panel panel6;
    private javax.swing.JTable tblAlternatif;
    private javax.swing.JTable tblNormalisasi;
    private javax.swing.JTable tblPerangkingan;
    private javax.swing.JTextField tfNama;
    // End of variables declaration//GEN-END:variables
public void tabelmodel(){
       tb =new DefaultTableModel();
       tb.addColumn("Nama");
       tb.addColumn("Kreteria 1");
       tb.addColumn("Kreteria 2");
       tb.addColumn("Kreteria 3");
       tb.addColumn("Kreteria 4");
       tb.addColumn("Kreteria 5");
       tb.addColumn("Kreteria 6");
       tb.addColumn("Kreteria 7");
       tb.addColumn("Kreteria 8");
       tb.addColumn("Kreteria 9");
       tb.addColumn("Kreteria 10");
       tblAlternatif.setModel(tb);
        try {
           
   
         ResultSet res = conn.ambilData("select *from tbl_alternatif ");
        while (res.next()){
                    tb.addRow(
                            new Object[]{                                
                                res.getString(2),
                                res.getString(3),
                                res.getString(4),
                                res.getString(5),
                                res.getString(6),
                                res.getString(7),
                                res.getString(8),
                                res.getString(9),
                                res.getString(10),
                                res.getString(11),
                                res.getString(12)
                            });
                } 
      
        tblAlternatif.setModel(tb);
          } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, ex);
        }   
     }
public void tabelmodelnormalisasi(){
       tb2 =new DefaultTableModel();
//       tb2.addColumn("No.");
       tb2.addColumn("Nama");
       tb2.addColumn("Kreteria 1");
       tb2.addColumn("Kreteria 2");
       tb2.addColumn("Kreteria 3");
       tb2.addColumn("Kreteria 4");
       tb2.addColumn("Kreteria 5");
       tb2.addColumn("Kreteria 6");
       tb2.addColumn("Kreteria 7");
       tb2.addColumn("Kreteria 8");
       tb2.addColumn("Kreteria 9");
       tb2.addColumn("Kreteria 10");
       tblNormalisasi.setModel(tb2);
       }
public  void normalisasi(){
       LinkedList max=new LinkedList();
       LinkedList mm=new LinkedList();
   try {
           
   
         ResultSet res = conn.ambilData("select 	max(C1),"+ 
                 "max(C2), "+
                 "max(C3), "+
                 "max(C4), "+
                 "max(C5), "+
                 "max(C6), "+
                 "max(C7), "+
                 "max(C8), "+
                 "max(C9), "+
                 "max(C10)"+
	"from "+
	"tbl_alternatif ");
        while (res.next()){
                    max.add(res.getString(1));
                    max.add(res.getString(2));
                    max.add(res.getString(3));
                    max.add(res.getString(4));
                    max.add(res.getString(5));
                    max.add(res.getString(6));
                    max.add(res.getString(7));
                    max.add(res.getString(8));
                    max.add(res.getString(9));
                    max.add(res.getString(10));
                } 
        ResultSet res2 = conn.ambilData("select *"+
	"from "+
	"tbl_alternatif ");
        tabelmodelnormalisasi();
        while (res2.next()){
            tb2.addRow(new Object[]{
//                res2.getString(1),
                res2.getString(2),
                (res2.getFloat(3)/Float.valueOf(max.get(0).toString())),
                (res2.getFloat(4)/Float.valueOf(max.get(1).toString())),
                (res2.getFloat(5)/Float.valueOf(max.get(2).toString())),
                (res2.getFloat(6)/Float.valueOf(max.get(3).toString())),
                (res2.getFloat(7)/Float.valueOf(max.get(4).toString())),
                (res2.getFloat(8)/Float.valueOf(max.get(5).toString())),
                (res2.getFloat(9)/Float.valueOf(max.get(6).toString())),
                (res2.getFloat(10)/Float.valueOf(max.get(7).toString())),
                (res2.getFloat(11)/Float.valueOf(max.get(8).toString())),
                (res2.getFloat(12)/Float.valueOf(max.get(9).toString()))
                
            });
                          
        }  
      
           } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, ex);
        }   
   }
public void tabelmodelPERINGKAT(){
        try {
            tb3 =new DefaultTableModel();
            tb3.addColumn("NAMA");
            tb3.addColumn("NILAI ");
            tblPerangkingan.setModel(tb3);
               ResultSet res = conn.ambilData("select *from tbl_peringkat order by nilai desc");
             while (res.next()){
                         tb3.addRow(new Object[]{res.getString(1),res.getString(2)}); 
                     }
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
   public void cariperingkat(){
        try {
            
       LinkedList mm=new LinkedList();
            ResultSet res3 = conn.ambilData("select * from tbl_bobot");
               tabelmodelPERINGKAT();
               while (res3.next()){
                           mm.add(res3.getString(1));
                           mm.add(res3.getString(2));
                           mm.add(res3.getString(3));
                           mm.add(res3.getString(4));
                           mm.add(res3.getString(5));
                           mm.add(res3.getString(6));
                           mm.add(res3.getString(7));
                           mm.add(res3.getString(8));
                           mm.add(res3.getString(9));
                           mm.add(res3.getString(10));
               }
            for (int t = 0; t < tblNormalisasi.getRowCount(); t++) {
              
            String sql = "delete from tbl_peringkat WHERE Nama= Nama";
               conn.simpanData(sql);
            }
            for (int x = 0; x < tblNormalisasi.getRowCount(); x++) {
               double r1;
               double r2;
               double r3;
               double r4;
               double r5;
               double r6;
               double r7;
               double r8;
               double r9;
               double r10;
               double w;
                r1=(Float.valueOf(tblNormalisasi.getValueAt(x, 1).toString())*Float.valueOf(mm.get(0).toString()));
                r2=(Float.valueOf(tblNormalisasi.getValueAt(x, 2).toString())*Float.valueOf(mm.get(1).toString()));
                r3=(Float.valueOf(tblNormalisasi.getValueAt(x, 3).toString())*Float.valueOf(mm.get(2).toString()));
                r4=(Float.valueOf(tblNormalisasi.getValueAt(x, 4).toString())*Float.valueOf(mm.get(3).toString()));
                r5=(Float.valueOf(tblNormalisasi.getValueAt(x, 5).toString())*Float.valueOf(mm.get(4).toString()));
                r6=(Float.valueOf(tblNormalisasi.getValueAt(x, 6).toString())*Float.valueOf(mm.get(5).toString()));
                r7=(Float.valueOf(tblNormalisasi.getValueAt(x, 7).toString())*Float.valueOf(mm.get(6).toString()));
                r8=(Float.valueOf(tblNormalisasi.getValueAt(x, 8).toString())*Float.valueOf(mm.get(7).toString()));
                r9=(Float.valueOf(tblNormalisasi.getValueAt(x, 9).toString())*Float.valueOf(mm.get(8).toString()));
                r10=(Float.valueOf(tblNormalisasi.getValueAt(x, 10).toString())*Float.valueOf(mm.get(9).toString()));
                
                w=r1+r2+r3+r4+r5+r6+r7+r8+r9+r10;
            String sql = "insert into tbl_peringkat  values"+
             "('"+tblNormalisasi.getValueAt(x, 0).toString()+"', "+
             "'"+w+"')";
               conn.simpanData(sql);
            }
            tabelmodelPERINGKAT();
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, ex);
        }
       }
   public int simpan(){
       String nama = tfNama.getText();
       tb1();
       tb2();
       tb3();
       tb4();
       tb5();
       tb6();
       tb7();
       tb8();
       tb9();
       tb10();
       
       
        String sql="insert into tbl_Alternatif values(NULL,'"+ nama +"','"+ bb1 +"','" + bb2 + "','"+ bb3 +"','" + bb4 +"','" + bb5 +"','"+ bb6 +"','" +bb7+"','"+ bb8 +"','" + bb9 + "','" + bb10+"')";               
        conn.simpanData(sql);
       return 0;
    }
   public int tb1(){
       if(cbPenghasilan.getSelectedItem().equals("1-<3 Juta")){
            bb1 = 1;
        }else if(cbPenghasilan.getSelectedItem().equals("3-<5 juta")){
            bb1 = 2;
        }else if(cbPenghasilan.getSelectedItem().equals("5-<7 juta")){
            bb1 = 3;
        }else if(cbPenghasilan.getSelectedItem().equals(">9 Juta")){
            bb1 = 4;
        }else{
            JOptionPane.showMessageDialog(null,"Pilih Penghasilan");
        }
       return 0;
   }
   public int tb2(){
       if(cbJaminan.getSelectedItem().equals("<10 Juta")){
            bb2 = 1;
        }else if(cbJaminan.getSelectedItem().equals(">10 Juta - 25 Juta")){
            bb2 = 2;
        }else if(cbJaminan.getSelectedItem().equals(">25 Juta - 35 Juta")){
            bb2 = 3;
        }else if(cbJaminan.getSelectedItem().equals(">35 Juta - 50 Juta")){
            bb2 = 4;
        }else if(cbJaminan.getSelectedItem().equals(">50 Juta")){
            bb2 = 5;
        }else{
            JOptionPane.showMessageDialog(null,"Pilih Jaminan");
        }
       return 0;
   }
   public int tb3(){
       if(cbStatus.getSelectedItem().equals("Milik Bersama")){
            bb3 = 1;
        }else if(cbStatus.getSelectedItem().equals("Milik Keluarga")){
            bb3 = 2;
        }else if(cbStatus.getSelectedItem().equals("Milik Pribadi")){
            bb3 = 3;
        }else{
            JOptionPane.showMessageDialog(null,"Pilih Status Usaha");
        }
       return 0;
   }
    public int tb4(){
       if(cbKondisi.getSelectedItem().equals("Usaha Macet")){
            bb4 = 1;
        }else if(cbKondisi.getSelectedItem().equals("Usaha Diragukan")){
            bb4 = 2;
        }else if(cbKondisi.getSelectedItem().equals("Usaha Mulai Berkembang")){
            bb4 = 3;
        }else if(cbKondisi.getSelectedItem().equals("Usaha Berkembang")){
            bb4 = 4;
        }else if(cbKondisi.getSelectedItem().equals("Usaha Berkembang Pesat")){
            bb4 = 5;
        }else{
            JOptionPane.showMessageDialog(null,"Pilih Kondisi Usaha");
        }
       return 0;
   }
    public int tb5(){
       if(cbKepribadian.getSelectedItem().equals("Sangat Kurang")){
            bb5 = 1;
        }else if(cbKepribadian.getSelectedItem().equals("Kurang")){
            bb5 = 2;
        }else if(cbKepribadian.getSelectedItem().equals("Cukup")){
            bb5 = 3;
        }else if(cbKepribadian.getSelectedItem().equals("Baik")){
            bb5 = 4;
        }else if(cbKepribadian.getSelectedItem().equals("Sangat Baik")){
            bb5 = 5;
        }else{
            JOptionPane.showMessageDialog(null,"Pilih Kepribadian Nasabah");
        }
       return 0;
   }
    public int tb6(){
       if(cbHarta.getSelectedItem().equals(">25 Juta")){
            bb6 = 1;
        }else if(cbHarta.getSelectedItem().equals(">50 Juta")){
            bb6 = 2;
        }else if(cbHarta.getSelectedItem().equals(">75 Juta")){
            bb6 = 3;
        }else if(cbHarta.getSelectedItem().equals(">100 Juta")){
            bb6 = 4;
        }else if(cbHarta.getSelectedItem().equals(">125 Juta")){
            bb6 = 5;
        }else{
            JOptionPane.showMessageDialog(null,"Pilih Harta Milik");
        }
       return 0;
   }
    public int tb7(){
       if(cbKemampuan.getSelectedItem().equals("Sangat Kurang")){
            bb7 = 1;
        }else if(cbKemampuan.getSelectedItem().equals("Kurang")){
            bb7 = 2;
        }else if(cbKemampuan.getSelectedItem().equals("Cukup")){
            bb7 = 3;
        }else if(cbKemampuan.getSelectedItem().equals("Baik")){
            bb7 = 4;
        }else if(cbKemampuan.getSelectedItem().equals("Sangat Baik")){
            bb7 = 5;
        }else{
            JOptionPane.showMessageDialog(null,"Pilih Kemampuan Melunasi Hutang");
        }
       return 0;
   }
    public int tb8(){
       if(cbTanggungan.getSelectedItem().equals(">11 Orang")){
            bb8 = 1;
        }else if(cbTanggungan.getSelectedItem().equals("9-11 Orang")){
            bb8 = 2;
        }else if(cbTanggungan.getSelectedItem().equals("6-8 Orang")){
            bb8 = 3;
        }else if(cbTanggungan.getSelectedItem().equals("3-5 Orang")){
            bb8 = 4;
        }else if(cbTanggungan.getSelectedItem().equals("1-2 Orang")){
            bb8 = 5;
        }else{
            JOptionPane.showMessageDialog(null,"Pilih Jumlah Tanggungan Hidup");
        }
       return 0;
   }
    public int tb9(){
       if(cbKepemilikan.getSelectedItem().equals("Kontrak")){
            bb9 = 1;
        }else if(cbKepemilikan.getSelectedItem().equals("Ikut Orang Tua")){
            bb9 = 2;
        }else if(cbKepemilikan.getSelectedItem().equals("Milik Pribadi")){
            bb9 = 3;
        }else{
            JOptionPane.showMessageDialog(null,"Pilih Kepemilikan Rumah");
        }
       return 0;
   }
    public int tb10(){
       if(cbPTambahan.getSelectedItem().equals(">1 Juta")){
            bb10 = 1;
        }else if(cbPTambahan.getSelectedItem().equals(">2 Juta")){
            bb10 = 2;
        }else if(cbPTambahan.getSelectedItem().equals(">3 Juta")){
            bb10 = 3;
        }else if(cbPTambahan.getSelectedItem().equals(">4 Juta")){
            bb10 = 4;
        }else if(cbPTambahan.getSelectedItem().equals(">5 Juta")){
            bb10 = 5;
        }else{
            JOptionPane.showMessageDialog(null,"Pilih Penghasilan Tambahan");
        }
       return 0;
   }
}